### ISSUE TITLE
CentOS EOL - Container Cannot Be Built

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/rawtoaces#141]
Noting that CentOS reached EOL so we get this now when building the container: "Could not resolve host: mirrorlist.centos.org; Unknown error"

**Comment by lgritz** [comment]
Solution: https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4325

**Comment by KelSolaar** [comment]
Thx Larry, I have seen the magic on SO!
